package cluster

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PortMapping publishes a node port on a host port.
//
// This is the only way a browser can open a Cloud Run URL: the tunnels used
// for the SDK endpoints are `kubectl port-forward`, which cannot serve a
// gateway that routes by Host header for arbitrary services.
type PortMapping struct {
	// HostPort is the port published on the host. It must be concrete: kind
	// cannot be asked to choose one and report it back.
	HostPort int
	// NodePort is the NodePort inside the cluster.
	NodePort int
	// ListenAddress is the host address to bind. Empty means 127.0.0.1, which
	// keeps the gateway off the LAN.
	ListenAddress string
	// Protocol is TCP when empty.
	Protocol string
}

// ConfigFileName is the kind configuration CloudBurrow generates.
const ConfigFileName = "kind.yaml"

// RenderConfig produces a kind cluster configuration.
//
// Only the mappings are configurable. The node image is passed to `kind
// create` as a flag and is deliberately not duplicated here, so there is one
// place it can be wrong.
func RenderConfig(mappings []PortMapping) string {
	var b strings.Builder
	b.WriteString("# Generated by CloudBurrow. Edits are overwritten on the next `up`.\n")
	b.WriteString("#\n")
	b.WriteString("# extraPortMappings are applied only when the cluster is created. Changing\n")
	b.WriteString("# them requires `cloudburrow delete` followed by `cloudburrow up`.\n")
	b.WriteString("apiVersion: kind.x-k8s.io/v1alpha4\n")
	b.WriteString("kind: Cluster\n")
	b.WriteString("nodes:\n")
	b.WriteString("  - role: control-plane\n")
	if len(mappings) == 0 {
		return b.String()
	}
	b.WriteString("    extraPortMappings:\n")
	for _, m := range mappings {
		listen := m.ListenAddress
		if listen == "" {
			listen = "127.0.0.1"
		}
		proto := m.Protocol
		if proto == "" {
			proto = "TCP"
		}
		fmt.Fprintf(&b, "      - containerPort: %d\n", m.NodePort)
		fmt.Fprintf(&b, "        hostPort: %d\n", m.HostPort)
		fmt.Fprintf(&b, "        listenAddress: %q\n", listen)
		fmt.Fprintf(&b, "        protocol: %s\n", proto)
	}
	return b.String()
}

// WriteConfig writes a kind configuration into dir and returns its path.
//
// It is written beside the kubeconfig rather than into a temporary file so
// that a developer debugging a cluster can see exactly what created it.
func WriteConfig(dir string, mappings []PortMapping) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create cluster config directory: %w", err)
	}
	path := filepath.Join(dir, ConfigFileName)
	if err := os.WriteFile(path, []byte(RenderConfig(mappings)), 0o644); err != nil {
		return "", fmt.Errorf("write cluster config: %w", err)
	}
	return path, nil
}
