package cluster

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderConfigPublishesTheMapping(t *testing.T) {
	t.Parallel()
	got := RenderConfig([]PortMapping{{HostPort: 9080, NodePort: 31080}})

	for _, want := range []string{
		"apiVersion: kind.x-k8s.io/v1alpha4",
		"kind: Cluster",
		"role: control-plane",
		"extraPortMappings:",
		"containerPort: 31080",
		"hostPort: 9080",
		`listenAddress: "127.0.0.1"`,
		"protocol: TCP",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("rendered config is missing %q:\n%s", want, got)
		}
	}
}

// A published port must not default to the LAN. Every service deployed into
// the cluster is reachable through this gateway, and exposing them to the
// network is not a trade a developer opted into.
func TestRenderConfigDefaultsToLoopback(t *testing.T) {
	t.Parallel()
	got := RenderConfig([]PortMapping{{HostPort: 9080, NodePort: 31080}})
	if !strings.Contains(got, `listenAddress: "127.0.0.1"`) {
		t.Errorf("a mapping with no listen address was not bound to loopback:\n%s", got)
	}
	if strings.Contains(got, `listenAddress: "0.0.0.0"`) {
		t.Error("a mapping defaulted to every interface")
	}
}

func TestRenderConfigHonoursAnExplicitListenAddress(t *testing.T) {
	t.Parallel()
	got := RenderConfig([]PortMapping{{HostPort: 9080, NodePort: 31080, ListenAddress: "0.0.0.0"}})
	if !strings.Contains(got, `listenAddress: "0.0.0.0"`) {
		t.Errorf("an explicit listen address was ignored:\n%s", got)
	}
}

// No mappings must still produce a usable cluster config: an instance with no
// ingress port is a supported configuration, not an error.
func TestRenderConfigWithNoMappingsIsStillValid(t *testing.T) {
	t.Parallel()
	got := RenderConfig(nil)
	if !strings.Contains(got, "role: control-plane") {
		t.Errorf("config without mappings is not a cluster:\n%s", got)
	}
	// The key, not the word: the header comment mentions extraPortMappings.
	if strings.Contains(got, "extraPortMappings:") {
		t.Errorf("an empty mapping list produced an empty extraPortMappings block:\n%s", got)
	}
}

// The node image belongs to the `kind create` flag and must not be duplicated
// here, or there are two places it can be wrong.
func TestRenderConfigDoesNotPinTheNodeImage(t *testing.T) {
	t.Parallel()
	if got := RenderConfig(nil); strings.Contains(got, "image:") {
		t.Errorf("the config pins a node image:\n%s", got)
	}
}

// The file says the mapping cannot be changed in place, because a developer
// who edits it and re-runs `up` would otherwise see no effect and no reason.
func TestRenderConfigSaysItIsGeneratedAndFixedAtCreation(t *testing.T) {
	t.Parallel()
	got := RenderConfig(nil)
	if !strings.Contains(got, "Generated by CloudBurrow") {
		t.Error("the generated file does not say it is generated")
	}
	if !strings.Contains(got, "cloudburrow delete") {
		t.Error("the file does not say how to change the mapping")
	}
}

func TestWriteConfigCreatesTheDirectoryAndFile(t *testing.T) {
	t.Parallel()
	dir := filepath.Join(t.TempDir(), "instance")

	path, err := WriteConfig(dir, []PortMapping{{HostPort: 9080, NodePort: 31080}})
	if err != nil {
		t.Fatalf("WriteConfig: %v", err)
	}
	if filepath.Base(path) != ConfigFileName {
		t.Errorf("wrote %q, want %s", path, ConfigFileName)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !strings.Contains(string(body), "hostPort: 9080") {
		t.Errorf("file does not contain the mapping:\n%s", body)
	}
}

// `up` regenerates the file every run, so a stale mapping from a previous
// configuration must not survive.
func TestWriteConfigOverwrites(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	if _, err := WriteConfig(dir, []PortMapping{{HostPort: 1111, NodePort: 31080}}); err != nil {
		t.Fatal(err)
	}
	path, err := WriteConfig(dir, []PortMapping{{HostPort: 2222, NodePort: 31080}})
	if err != nil {
		t.Fatal(err)
	}
	body, _ := os.ReadFile(path)
	if strings.Contains(string(body), "1111") {
		t.Errorf("the previous mapping survived:\n%s", body)
	}
	if !strings.Contains(string(body), "2222") {
		t.Errorf("the new mapping was not written:\n%s", body)
	}
}

func TestWriteConfigReportsAnUnusableDirectory(t *testing.T) {
	t.Parallel()
	// A file where the directory should be: creating it must fail loudly
	// rather than leave `kind create` without a config it was promised.
	file := filepath.Join(t.TempDir(), "afile")
	if err := os.WriteFile(file, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := WriteConfig(filepath.Join(file, "sub"), nil); err == nil {
		t.Fatal("WriteConfig succeeded into a path that is a file")
	}
}
