package storage

// status says whether a discovery method is served.
type status int

const (
	unimplemented status = iota
	built
)

// methodStatus lists every method in the discovery document, and only those
// (TestStorageDiscoveryDrift). A method moves to built in the issue that
// implements it; until then it answers 501 notImplemented naming it, never a
// plausible stub. Buckets are built (#490), objects.insert, get and delete (#491), objects.patch and update (#492), objects.list (#494), and compose, copy, rewrite and move (#495).
var methodStatus = map[string]status{
	"storage.anywhereCaches.disable":                   unimplemented,
	"storage.anywhereCaches.get":                       unimplemented,
	"storage.anywhereCaches.insert":                    unimplemented,
	"storage.anywhereCaches.list":                      unimplemented,
	"storage.anywhereCaches.pause":                     unimplemented,
	"storage.anywhereCaches.resume":                    unimplemented,
	"storage.anywhereCaches.update":                    unimplemented,
	"storage.bucketAccessControls.delete":              unimplemented,
	"storage.bucketAccessControls.get":                 unimplemented,
	"storage.bucketAccessControls.insert":              unimplemented,
	"storage.bucketAccessControls.list":                unimplemented,
	"storage.bucketAccessControls.patch":               unimplemented,
	"storage.bucketAccessControls.update":              unimplemented,
	"storage.buckets.delete":                           built,
	"storage.buckets.get":                              built,
	"storage.buckets.getIamPolicy":                     built,
	"storage.buckets.getStorageLayout":                 unimplemented,
	"storage.buckets.insert":                           built,
	"storage.buckets.list":                             built,
	"storage.buckets.lockRetentionPolicy":              built,
	"storage.buckets.operations.advanceRelocateBucket": unimplemented,
	"storage.buckets.operations.cancel":                unimplemented,
	"storage.buckets.operations.get":                   unimplemented,
	"storage.buckets.operations.list":                  unimplemented,
	"storage.buckets.patch":                            built,
	"storage.buckets.relocate":                         unimplemented,
	"storage.buckets.restore":                          built,
	"storage.buckets.setIamPolicy":                     built,
	"storage.buckets.testIamPermissions":               built,
	"storage.buckets.update":                           built,
	"storage.channels.stop":                            unimplemented,
	"storage.defaultObjectAccessControls.delete":       unimplemented,
	"storage.defaultObjectAccessControls.get":          unimplemented,
	"storage.defaultObjectAccessControls.insert":       unimplemented,
	"storage.defaultObjectAccessControls.list":         unimplemented,
	"storage.defaultObjectAccessControls.patch":        unimplemented,
	"storage.defaultObjectAccessControls.update":       unimplemented,
	"storage.folders.delete":                           unimplemented,
	"storage.folders.deleteRecursive":                  unimplemented,
	"storage.folders.get":                              unimplemented,
	"storage.folders.insert":                           unimplemented,
	"storage.folders.list":                             unimplemented,
	"storage.folders.rename":                           unimplemented,
	"storage.managedFolders.delete":                    unimplemented,
	"storage.managedFolders.get":                       unimplemented,
	"storage.managedFolders.getIamPolicy":              unimplemented,
	"storage.managedFolders.insert":                    unimplemented,
	"storage.managedFolders.list":                      unimplemented,
	"storage.managedFolders.setIamPolicy":              unimplemented,
	"storage.managedFolders.testIamPermissions":        unimplemented,
	"storage.managedFolders.update":                    unimplemented,
	"storage.notifications.delete":                     unimplemented,
	"storage.notifications.get":                        unimplemented,
	"storage.notifications.insert":                     unimplemented,
	"storage.notifications.list":                       unimplemented,
	"storage.objectAccessControls.delete":              unimplemented,
	"storage.objectAccessControls.get":                 unimplemented,
	"storage.objectAccessControls.insert":              unimplemented,
	"storage.objectAccessControls.list":                unimplemented,
	"storage.objectAccessControls.patch":               unimplemented,
	"storage.objectAccessControls.update":              unimplemented,
	"storage.objects.bulkRestore":                      unimplemented,
	"storage.objects.compose":                          built,
	"storage.objects.copy":                             built,
	"storage.objects.delete":                           built,
	"storage.objects.get":                              built,
	"storage.objects.getIamPolicy":                     unimplemented,
	"storage.objects.insert":                           built,
	"storage.objects.list":                             built,
	"storage.objects.move":                             built,
	"storage.objects.patch":                            built,
	"storage.objects.restore":                          built,
	"storage.objects.rewrite":                          built,
	"storage.objects.setIamPolicy":                     unimplemented,
	"storage.objects.testIamPermissions":               unimplemented,
	"storage.objects.update":                           built,
	"storage.projects.hmacKeys.create":                 built,
	"storage.projects.hmacKeys.delete":                 built,
	"storage.projects.hmacKeys.get":                    built,
	"storage.projects.hmacKeys.list":                   built,
	"storage.projects.hmacKeys.update":                 built,
	"storage.projects.serviceAccount.get":              built,
	"storage.rapidCaches.disable":                      unimplemented,
	"storage.rapidCaches.get":                          unimplemented,
	"storage.rapidCaches.insert":                       unimplemented,
	"storage.rapidCaches.list":                         unimplemented,
	"storage.rapidCaches.update":                       unimplemented,
}
