#!/bin/sh
# Render the Homebrew formula for a release from its checksums.txt.
#
#   sh scripts/render-formula.sh v0.1.0 dist/checksums.txt > cloudburrow.rb
#
# The formula is generated rather than edited by hand, so the checksums it
# pins are the ones the release published, and it cannot fall behind one.

set -eu

[ $# -eq 2 ] || { echo "usage: render-formula.sh <tag> <checksums.txt>" >&2; exit 2; }
tag="$1"
sums="$2"
repo="cloudburrow/cloudburrow"

sum() {
	f="cloudburrow_${tag}_$1.tar.gz"
	s="$(awk -v f="$f" '$2 == f || $2 == "*" f { print $1 }' "$sums")"
	[ -n "$s" ] || { echo "render-formula.sh: no checksum for $f in $sums" >&2; exit 1; }
	printf '%s' "$s"
}
url() { printf 'https://github.com/%s/releases/download/%s/cloudburrow_%s_%s.tar.gz' "$repo" "$tag" "$tag" "$1"; }

darwin_arm64="$(sum darwin_arm64)"
darwin_amd64="$(sum darwin_amd64)"
linux_arm64="$(sum linux_arm64)"
linux_amd64="$(sum linux_amd64)"

cat <<EOF
# Generated by scripts/render-formula.sh for ${tag}. Do not edit by hand.
class Cloudburrow < Formula
  desc "Local Google Cloud emulator for development and testing"
  homepage "https://github.com/${repo}"
  version "${tag#v}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url darwin_arm64)"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "$(url darwin_amd64)"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux_arm64)"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "$(url linux_amd64)"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "cloudburrow"
  end

  test do
    assert_match "cloudburrow ${tag}", shell_output("#{bin}/cloudburrow version")
  end
end
EOF
