package main

import (
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/cloudburrow/cloudburrow/internal/config"
	"github.com/cloudburrow/cloudburrow/internal/netfwd"
)

// The environment a pod is given (#576): the same variables `env` exports
// for the host, with the addresses a pod reaches — the emulators' Service
// names and, for what the CLI serves, the cloudburrow-host name (#575).
// The Cloud Run adapter injects it into every revision and job task, and
// `env --format kubernetes` prints it, both from podEnvVars, so the two
// cannot disagree.

// cliEndpointVar is the CLOUDBURROW_*_ENDPOINT variable of a service the CLI
// serves, or "" for one with none. No client library reads these; they are
// for code that builds its own channel, as docs/credentials.md shows.
func cliEndpointVar(service string) string {
	switch service {
	case "tasks":
		return "CLOUDBURROW_TASKS_ENDPOINT"
	case "secretmanager":
		return "CLOUDBURROW_SECRETMANAGER_ENDPOINT"
	case "kms":
		return "CLOUDBURROW_KMS_ENDPOINT"
	case "scheduler":
		return "CLOUDBURROW_SCHEDULER_ENDPOINT"
	case "logging":
		return "CLOUDBURROW_LOGGING_ENDPOINT"
	case "resourcemanager":
		return "CLOUDBURROW_RESOURCEMANAGER_ENDPOINT"
	case "run":
		// Cloud Run v2, gRPC and JSON (#661), for code that deploys or lists
		// services; given to pods too, since the adapter is published to them
		// through cloudburrow-host (#707).
		return "CLOUDBURROW_RUN_ENDPOINT"
	}
	return ""
}

// podEnvVars maps in-cluster addresses, by service, to the variables that
// point a pod's clients at them, in name order.
//
// A service with no variable (Cloud SQL, Memorystore) is
// left out, as is an empty address: a variable set empty reads as unset in
// most clients, which then reach Google. Nothing here is a credential. The
// host's credentials fixture is a host path and is never included; a pod
// asks the metadata server, at GCE_METADATA_HOST, for a token instead.
func podEnvVars(inCluster map[string]string) []envVar {
	var vars []envVar
	for service, addr := range inCluster {
		// Only a cluster-local name: a host address, which is all a
		// service not yet published has, is one a pod cannot reach.
		if !isInClusterAddr(addr) {
			continue
		}
		switch {
		case netfwd.EnvVarFor(service) != "":
			vars = append(vars, envVar{netfwd.EnvVarFor(service), netfwd.EnvValueFor(service, addr),
				"read by the official " + service + " clients"})
		case service == "bigquery":
			vars = append(vars, envVar{"CLOUDBURROW_BIGQUERY_ENDPOINT", "http://" + addr,
				"read by no client library: pass it to option.WithEndpoint"})
		case service == "bigquery-storage":
			vars = append(vars, envVar{"CLOUDBURROW_BIGQUERY_STORAGE_ENDPOINT", addr,
				"the Storage Read API (gRPC); read by no client library"})
		case service == "metadata":
			vars = append(vars, envVar{"GCE_METADATA_HOST", addr,
				"the metadata server: project, and tokens that authorise nothing"})
		case cliEndpointVar(service) != "":
			vars = append(vars, envVar{cliEndpointVar(service), addr,
				"gRPC, plaintext; read by no client library: give it to a channel in code"})
		}
	}
	sort.Slice(vars, func(i, j int) bool { return vars[i].Name < vars[j].Name })
	return vars
}

// targetKey is the service name a tunnel's in-cluster address is known by:
// its label where it has one (bigquery-storage), else its Service's name.
func targetKey(t netfwd.Target) string {
	if t.Label != "" {
		return t.Label
	}
	return t.Name
}

// writeKubernetesEnv prints a container's `env:` list.
//
// A list rather than a ConfigMap: it pastes under a container as it is and
// needs no second object to apply and keep in step, and it is the form the
// Cloud Run adapter injects. The values are quoted so a port is a string,
// as Kubernetes requires.
func writeKubernetesEnv(w io.Writer, instance string, vars []envVar) {
	fmt.Fprintln(w, "# Paste under a container in a Kubernetes manifest. Generated by `cloudburrow env --format kubernetes`")
	fmt.Fprintf(w, "# for the running instance %q: in-cluster addresses, which only a pod in its cluster can use.\n", instance)
	fmt.Fprintln(w, "# Cloud Run services deployed through CloudBurrow are given these already.")
	fmt.Fprintln(w, "env:")
	for _, v := range vars {
		fmt.Fprintf(w, "  - name: %s\n    value: %s\n", v.Name, strconv.Quote(v.Value))
	}
}

// podEnvMap is podEnvVars as the Cloud Run adapter takes it.
func podEnvMap(inCluster map[string]string) map[string]string {
	out := map[string]string{}
	for _, v := range podEnvVars(inCluster) {
		out[v.Name] = v.Value
	}
	return out
}

// isInClusterAddr reports whether addr is a cluster-local name, rather
// than a host address a pod could not reach.
func isInClusterAddr(addr string) bool {
	host, _, _ := strings.Cut(addr, ":")
	return strings.HasSuffix(host, ".svc.cluster.local")
}

// podAddresses is every in-cluster address a running `up` knows: each
// tunnel's backend Service and each service published through
// cloudburrow-host. A service host has not published yet is absent.
func podAddresses(fwds []*netfwd.Forwarder, host *clusterHost) map[string]string {
	out := map[string]string{}
	for _, f := range fwds {
		out[strings.TrimPrefix(f.Name(), "forward:")] = f.InClusterAddr()
	}
	for k, v := range host.InClusterAll() {
		out[k] = v
	}
	return out
}

// kubernetesEnvVars is what `env --format kubernetes` prints for a running
// instance: the pod environment of every service it recorded as bound —
// its own services, not whatever this invocation's flags enable — and its
// project.
//
// A tunnelled backend's in-cluster address is its Service's name and port,
// which are fixed by the service, so it is derived; the CLI-hosted services'
// are what the instance recorded as published through cloudburrow-host.
func kubernetesEnvVars(cfg config.Config, info runtimeInfo, project string) []envVar {
	addrs := map[string]string{}
	for _, s := range config.KnownServices() {
		for _, t := range forwardTargets(cfg, s) {
			if _, bound := info.Endpoints[targetKey(t)]; bound {
				addrs[targetKey(t)] = t.InClusterAddr()
			}
		}
	}
	for k, v := range info.InCluster {
		addrs[k] = v
	}
	vars := append(podEnvVars(addrs), envVar{"GOOGLE_CLOUD_PROJECT", project,
		"the project every local resource lives under"})
	sort.Slice(vars, func(i, j int) bool { return vars[i].Name < vars[j].Name })
	return vars
}
