package main

import (
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"syscall"

	"github.com/cloudburrow/cloudburrow/internal/config"
)

// `cloudburrow terraform` (#283): run Terraform or OpenTofu with the Google
// provider pointed at this instance.
//
// It writes a provider configuration next to the module, runs the binary with
// the remaining arguments, and removes the file however the run ends. Only
// services whose Terraform support is Verified in docs/compatibility.md get
// an endpoint; the rest are named in a warning rather than silently sent to
// real Google.

// terraformEndpoint is one provider endpoint attribute.
type terraformEndpoint struct {
	service config.Service
	attr    string // the google provider's *_custom_endpoint argument
	env     string // the environment variable the provider reads it from
	path    string // appended to http://host:port
	// verified is true only for rows docs/compatibility.md marks Verified
	// with a test behind them. `env --format terraform` reads this table too.
	verified bool
}

var terraformEndpoints = []terraformEndpoint{
	{config.ServiceStorage, "storage_custom_endpoint", "GOOGLE_STORAGE_CUSTOM_ENDPOINT", "/storage/v1/", true},
	{config.ServicePubSub, "pubsub_custom_endpoint", "GOOGLE_PUBSUB_CUSTOM_ENDPOINT", "/v1/", true},
	{config.ServiceTasks, "cloud_tasks_custom_endpoint", "GOOGLE_CLOUD_TASKS_CUSTOM_ENDPOINT", "/v2/", false},
	{config.ServiceSecrets, "secret_manager_custom_endpoint", "GOOGLE_SECRET_MANAGER_CUSTOM_ENDPOINT", "/v1/", false},
	{config.ServiceRun, "cloud_run_v2_custom_endpoint", "GOOGLE_CLOUD_RUN_V2_CUSTOM_ENDPOINT", "/v2/", false},
	// google_project (#301): Resource Manager v1, and the Cloud Billing read
	// the provider makes on every refresh, both served on the Resource
	// Manager port.
	{resourceManagerEndpoint, "resource_manager_custom_endpoint", "GOOGLE_RESOURCE_MANAGER_CUSTOM_ENDPOINT", "/v1/", true},
	{resourceManagerEndpoint, "cloud_billing_custom_endpoint", "GOOGLE_CLOUD_BILLING_CUSTOM_ENDPOINT", "/v1/", true},
}

// resourceManagerEndpoint keys the Resource Manager rows. It is not a
// selectable service: the project registry, and so its API, always runs.
const resourceManagerEndpoint config.Service = "resourcemanager"

// terraformAccessToken is what the provider presents. CloudBurrow
// authenticates nothing, so any token works; a fixed, obviously local one
// keeps the provider from looking for credentials of its own.
const terraformAccessToken = "cloudburrow-local-not-a-credential"

// generatedMarker heads every file this writes, so one left by a killed run
// is recognised as ours and a user's file of the same name never is.
const generatedMarker = "# Generated by `cloudburrow terraform`. Removed when it exits; do not edit."

// terraformURL is one endpoint the provider is given.
type terraformURL struct {
	terraformEndpoint
	url string
}

// terraformSettings resolves the table against an instance: the endpoints to
// set, and the enabled services deliberately left out. Both the provider file
// and `env --format terraform` are rendered from this, so they cannot differ.
func terraformSettings(cfg config.Config) ([]terraformURL, []config.Service) {
	host := func(port int) string { return net.JoinHostPort(cfg.BindAddress, strconv.Itoa(port)) }
	ports := map[config.Service]int{
		config.ServiceStorage: cfg.Endpoints.Storage, config.ServicePubSub: cfg.Endpoints.PubSub,
		config.ServiceTasks: cfg.Endpoints.Tasks, config.ServiceSecrets: cfg.Endpoints.Secrets, config.ServiceRun: cfg.Endpoints.Run,
		resourceManagerEndpoint: cfg.Endpoints.ResourceManager,
	}
	enabled := map[config.Service]bool{resourceManagerEndpoint: true}
	for _, s := range cfg.EnabledServices() {
		enabled[s] = true
	}
	var set []terraformURL
	var skipped []config.Service
	for _, e := range terraformEndpoints {
		if !enabled[e.service] {
			continue
		}
		if !e.verified || ports[e.service] == 0 {
			skipped = append(skipped, e.service)
			continue
		}
		set = append(set, terraformURL{e, "http://" + host(ports[e.service]) + e.path})
	}
	return set, skipped
}

// terraformProvider renders the provider configuration and names the
// enabled services it deliberately left out.
func terraformProvider(cfg config.Config, override bool) (string, []config.Service) {
	set, skipped := terraformSettings(cfg)
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n# Instance %q.\n", generatedMarker, cfg.Name)
	b.WriteString("provider \"google\" {\n")
	fmt.Fprintf(&b, "  project      = %q\n", cfg.DefaultProject())
	fmt.Fprintf(&b, "  access_token = %q\n", terraformAccessToken)
	if override {
		// An override merges into the module's own block, and the provider
		// refuses credentials alongside access_token.
		b.WriteString("  credentials  = null\n")
	}
	for _, e := range set {
		fmt.Fprintf(&b, "  %s = %q\n", e.attr, e.url)
	}
	b.WriteString("}\n")
	return b.String(), skipped
}

var googleProviderBlock = regexp.MustCompile(`(?m)^\s*provider\s+"google"\s*\{`)

// moduleDeclaresGoogle reports whether the module already configures the
// google provider. An override file needs a block to merge into, and a plain
// one would duplicate an existing block, so which file is written depends on
// the answer.
func moduleDeclaresGoogle(dir string) bool {
	files, _ := filepath.Glob(filepath.Join(dir, "*.tf"))
	for _, f := range files {
		if strings.HasPrefix(filepath.Base(f), "cloudburrow_providers") {
			continue
		}
		if b, err := os.ReadFile(f); err == nil && googleProviderBlock.Match(b) {
			return true
		}
	}
	return false
}

// terraformArgs splits `cloudburrow terraform [flags] [--] args...`.
// CloudBurrow's own flags come before "--". Without one, every argument is
// the binary's, and the instance is chosen by the environment and config
// file, as for any command.
func terraformArgs(args []string) (ours, theirs []string, binary string, err error) {
	for i, a := range args {
		if a == "--" {
			ours, theirs = args[:i], args[i+1:]
			break
		}
	}
	if theirs == nil {
		theirs, ours = args, nil
	}
	v, found, ours, err := splitFlag(ours, "binary", false)
	if err != nil {
		return nil, nil, "", err
	}
	binary = "terraform"
	if found {
		binary = v
	}
	return ours, theirs, binary, nil
}

// moduleDir is the directory Terraform will read, honouring -chdir.
func moduleDir(theirs []string) string {
	for _, a := range theirs {
		if dir, ok := strings.CutPrefix(a, "-chdir="); ok {
			return dir
		}
		if !strings.HasPrefix(a, "-") {
			break // the subcommand: -chdir must come before it
		}
	}
	return "."
}

func runTerraform(args []string, stdout, stderr io.Writer) error {
	ours, theirs, binary, err := terraformArgs(args)
	if err != nil {
		fmt.Fprintln(stderr, err)
		return errUsage
	}
	cfg, err := config.Load(config.Options{Args: ours, Output: stderr})
	if err != nil {
		return err
	}
	if info, ok := running(cfg); ok {
		cfg = withLivePorts(cfg, info.Endpoints)
	}

	dir := moduleDir(theirs)
	override := moduleDeclaresGoogle(dir)
	name := "cloudburrow_providers.tf"
	if override {
		name = "cloudburrow_providers_override.tf"
	}
	path := filepath.Join(dir, name)
	if b, err := os.ReadFile(path); err == nil && !strings.HasPrefix(string(b), generatedMarker) {
		return fmt.Errorf("%s exists and was not written by cloudburrow; refusing to replace it", path)
	}
	body, skipped := terraformProvider(cfg, override)
	for _, s := range skipped {
		fmt.Fprintf(stderr, "cloudburrow terraform: %s is enabled but has no Verified Terraform support, "+
			"so no endpoint is set for it; resources for it would go to real Google\n", s)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		return err
	}
	defer func() { _ = os.Remove(path) }()

	cmd := exec.Command(binary, theirs...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, stdout, stderr
	// Terraform handles Ctrl-C itself: the terminal delivers SIGINT to it
	// directly, and it stops cleanly and saves state. This process only has
	// to outlive it, so the file is removed afterwards rather than under a
	// run still reading it. SIGTERM, sent to this process alone, is passed on.
	sigs := make(chan os.Signal, 2)
	signal.Notify(sigs, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(sigs)
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("run %s: %w", binary, err)
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	for {
		select {
		case s := <-sigs:
			if s == syscall.SIGTERM {
				_ = cmd.Process.Signal(syscall.SIGTERM)
			}
		case err := <-done:
			var exit *exec.ExitError
			if errors.As(err, &exit) {
				// The binary's own status, and its own message already shown.
				return &exitError{code: exit.ExitCode(), err: err, quiet: true}
			}
			return err
		}
	}
}
